name: Deploy

on: 
  push:
    paths:
      - 'gamers.zip'
env:
  ITCH_USERNAME: handshou
  ITCH_GAME_ID: treeoflife
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - html
        template:
          - gamers.zip
    name: Deploy - Itch.io ${{ matrix.template }}
    steps:
      - uses: actions/checkout@v2
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ${{ matrix.template }}
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
